# Generated by Django 4.2.3 on 2023-08-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduTech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=100, null=True)),
                ('slug', models.CharField(default='', max_length=100, null=True)),
                ('desc', models.TextField(default='', max_length=200, null=True)),
                ('price', models.IntegerField(default=1, null=True)),
                ('discount', models.IntegerField(default=1, null=True)),
                ('course_image', models.ImageField(upload_to='static/images/')),
                ('resource', models.FileField(upload_to='resources/course/')),
                ('duration', models.TimeField()),
            ],
        ),
    ]
