# Generated by Django 4.2.3 on 2023-09-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EduTech', '0003_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_belong',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EduTech.course_details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='video_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
