# Generated by Django 4.2.3 on 2023-09-02 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EduTech', '0004_videos_video_belong_videos_video_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_belong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EduTech.course_details'),
        ),
    ]
