# Generated by Django 4.2.3 on 2023-09-04 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EduTech', '0007_user_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduTech.course_details')),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduTech.user_course')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduTech.signup')),
            ],
        ),
    ]
