# Generated by Django 4.2.3 on 2023-09-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EduTech', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EduTech.user_course'),
        ),
    ]
